### ISSUE TITLE
Layer - Add a 'Subtitle' to the Center Modal

### ISSUE THREAD

**Issue by Keeth-HPe** [grommet/hpe-design-system#2297]
We have a use case where a 'subtitle' for the center modal is needed. 
Here's an example :
<img width="442" alt="Screenshot 2022-02-01 at 11 20 47 PM" src="https://user-images.githubusercontent.com/86280029/152023056-73da993a-9d71-4f59-b0ad-b6bf7778ca67.png">

Currently, the center modal component in the Figma library and on the site does not have a subtitle, we need something similar to the 'Side Drawer Modal's example. 
<img width="378" alt="Screenshot 2022-02-01 at 11 09 38 PM" src="https://user-images.githubusercontent.com/86280029/152023519-4b7c1c66-6bf6-4905-9b60-87bb9c84a74f.png">

<img width="467" alt="Screenshot 2022-02-01 at 11 09 31 PM" src="https://user-images.githubusercontent.com/86280029/152023581-22f9e21e-6508-4a32-a569-3dc96f00e56d.png">

**Comment by Keeth-HPe** [comment]
@bahriaditi 

Please review the changes made: https://www.figma.com/file/Ts53TAipMolmsv9DxWG3p0/HPE-Layer-Component?node-id=2213%3A2734

Added the subtitle text to the 'dialog/center modal' component, also the 'side drawer modal' example in the finished page was not aligning to what was on the site. Made changes there as well.

**Comment by bahriaditi** [comment]
Hi @Keeth-HPe I like the subtitle addition, but the auto layout is a bit wonky in the Center Modal component. See screenshot. For Side Drawer, the subtitle doesn't wrap as expected. Once these are fixed, we can publish in Figma.

<img width="514" alt="Screen Shot 2022-02-08 at 9 50 11 AM" src="https://user-images.githubusercontent.com/87677275/153046456-3cdd65a2-6d36-48c5-9866-fcffbadbc450.png">

<img width="527" alt="Screen Shot 2022-02-08 at 9 49 25 AM" src="https://user-images.githubusercontent.com/87677275/153046489-a58aea27-3fea-4f53-9fc7-a4a61bf0635a.png">

<img width="657" alt="Screen Shot 2022-02-08 at 9 51 41 AM" src="https://user-images.githubusercontent.com/87677275/153046575-ecb379cc-b6df-419c-b558-7b44762e585c.png">

**Comment by Keeth-HPe** [comment]
@bahriaditi  Oops! Pasted the wrong component.  It's fixed now 👍

https://user-images.githubusercontent.com/86280029/153190357-98285251-0e50-4550-a712-cfceb28c1213.mov

**Comment by bahriaditi** [comment]
Hi @Keeth-HPe thank you - center modal looks great! ✅  
Side Drawer: I am still seeing that the side drawer subtitle and heading don't wrap when I put in longer text (more than one line)
